# Installs NextCloud instance on the box
# galaxy.ansible.com/nextcloud/admin
# GitHub link - https://github.com/nextcloud/ansible-collection-nextcloud-admin
- src: git+https://github.com/nextcloud/ansible-collection-nextcloud-admin.git
  version: main # branch name
  name: nextcloud.admin

# Installs php dependencies on the box
# galaxy.ansible.com/geerlingguy/php-versions
# GitHub link - https://github.com/geerlingguy/ansible-role-php-versions
- src: git+https://github.com/geerlingguy/ansible-role-php-versions.git
  version: 5.0.1 # branch name
  name: geerlingguy.php-versions

# Installs ansible utils  on the box
# galaxy.ansible.com/ansible-utils
# GitHub link - https://github.com/ansible-collections/ansible.utils
- src: git+https://github.com/ansible-collections/ansible.utils.git
  version: 2.9.0 # branch name
  name: ansible.utils

# Installs php dependencies on the box
# galaxy.ansible.com/geerlingguy/php-versions
# GitHub link - https://github.com/ansible-collections/community.general
- src: git+https://github.com/ansible-collections/community.general.git
  version: 6.5.0 # branch name
  name: community.general